import { StyleSheet } from "react-native";

const ExternalStyle = StyleSheet.create({
  container: {
    alignItems: "center",
    width: 350,
    boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
    margin: "5%",
    paddingBottom: "5%",
  },
  saveContainer: {
    width: 400,
    margin: "5%",
    paddingBottom: "5%",
  },
  menu: {
    flex: 1,
    flexDirection:'column',
    gap: 10,
    with: 250,
    height: 100,
    marginStart: 15,
    marginTop: 60,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 5,

  },
  menuBtn: {
    alignItems: "center",
    width: "120px",
    height: "20px",
    backgroundColor: "seagreen",
    borderRadius: "5px",
  },
  card: {
    alignItems: "left",
    padding: "5%",
    width: "90%",
    boxShadow:
      "0px 4px 4px rgba(0, 0, 0, 0.25),0px 4px 4px rgba(0, 0, 0, 0.25)",
    margin: "5%",
    paddingBottom: "5%",
  },
  headingStyle: {
    fontFamily: "Roboto",
    fontSize: "15px",
    fontWeight: "bold",
    marginBottom: 5,
  },
  btnImg: {
    width: 20,
    height: 20,
    marginLeft: "35%",
    marginTop: 20,
  },
  imageStyle: {
    width: 150,
    height: 150,
    marginTop: 10,
    borderRadius: "50%",
    border: "2px solid red",
  },
  circle: {
    width: 30,
    height: 30,
    marginTop: 10,
    borderRadius: "50%",
    border: "1px solid gray",
  },
  icon: {
    width: 30,
    height: 30,
  },
  verticalLine: {
    height: 30,
    width: 1,
    backgroundColor: "gray",
  },
  footer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "5%",
    paddingTop: 1,
    paddingStart: "4%",
  },
  name: {
    fontFamily: "Roboto",
    fontSize: "23px",
    color: " #000000",
    textShadow:
      "0px 4px 4px rgba(0, 0, 0, 0.25), 0px 4px 4px rgba(0, 0, 0, 0.25)",
    marginBottom: 25,
  },
  Input: {
    marginBottom: 20,
    width: "85%",
    height: 40,
    background: "#FFFFFF",
    boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
    borderRadius: "5px",
    paddingStart: "10%",
  },
  TextArea: {
    marginBottom: 20,
    width: "85%",
    height: 80,
    background: "#FFFFFF",
    boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
    borderRadius: "5px",
    paddingStart: "10%",
  },
  add: {
    width: 20,
    height: 20,
    background: "#FFFFFF",
    boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
    borderRadius: "50%",
    border: "1px solid gray",
    alignItems: "center",
    paddingBottom: 7,
    backgroundColor: "black",
    color: "white",
  },
  adding: {
    width: 120,
    height: 20,
    boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
    borderRadius: "5px",
    border: "1px solid gray",
    alignItems: "center",
    paddingBottom: 7,
    backgroundColor: "darkseagreen",
    color: "black",
    fontWeight: "bolder",
    marginStart: 185,
    marginBottom: 20,
  },
  Button: {
    marginBottom: 20,
    marginTop: 10,
    width: "85%",
    height: 40,
    backgroundColor: "darkseagreen",
    boxShadow:
      "0px 4px 4px rgba(0, 0, 0, 0.25),0px 4px 4px rgba(0, 0, 0, 0.25),0px 4px 4px rgba(0, 0, 0, 0.25)",
    borderRadius: "5px",
    alignItems: "center",
    paddingTop: 10,
    textTransform: "uppercase",
    fontWeight: "bold",
  },
});
export default ExternalStyle;
